stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data-processing:
    cmd: python src/data-preprocessing.py
    deps:
    - data/raw
    - src/data-preprocessing.py
    outs:
    - data/interim
  feature_engineering:
    cmd: python src/feature-enginerring.py
    deps:
    - data/interim
    - src/feature-enginerring.py
    params:
    - feature_engineering.max_features
    outs:
    - data/processed
  model_building:
    cmd: python src/model-building.py
    deps:
    - data/processed
    - src/model-building.py
    params:
    - model_building.n_estimators
    - model_building.random_state
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model-evaluation.py
    deps:
    - models/model.pkl
    - src/model-evaluation.py
    metrics:
    - reports/metrics.json
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
